name: Regions
main: ru.nukkit.regions.RegionsPlugin
version: "0.0.5/2"
author: fromgate, nukkit.ru
api: ["1.0.0"]
description: Regions, regions, regions!
permissions:
  regions.unlimited:
    descripition: Allows to operate with regions owned by other players
    default: op